### ISSUE TITLE
An interlude to compile "mak.sh"

### ISSUE THREAD

**Issue by NHW2017** [chenxy99/AttFDNet#2]
I ran into the following problems while compiling the "mak.sh" file:

running build_ext
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)

I think it may be caused by the mismatch of CUDA version, so I would like to ask which version of CUDA is adopted in the testing process

**Comment by chenxy99** [comment]
Hello, I remove some files that were compiled from my servers. Now you can try to use 'sh make.sh' to compile it again.

**Comment by NHW2017** [comment]
I'm sorry to disturb you again, I see in your implementation file used in training a "detection_collate" module, ,However, there is no such module in the file downloaded from GitHub.and then I in additional links "RFBNet" found it  in the data/voc0712 "def detection_collate", but there have been some problems to solve temporarily, if you convenient please give some help,  looking forward to your reply, thank you

**Comment by chenxy99** [comment]
Hello, I upload the function you mentioned and I also update the readme.md for you to easy to implement our models.
